drop table logEntries if exists;

create table logEntries (
    id integer generated by default as identity primary key,
    requestDate timestamp not null,
    ipAddress varchar(100) not null,
    request varchar(100) not null,
    status integer not null,
    userAgent varchar(200) not null
);

drop table searchResults if exists;

create table searchResults (
    ipAddress varchar(100) not null,
    count integer not null
);
